'use server'
import nodemailer from 'nodemailer';

interface SendCredentialsOptions {
    to: string;                // user's email
    firstName: string;
    lastName: string;
    password: string;          // plain text password (generated by backend)
    role?: string;             // optional, e.g., "ROLE_WAITER"
}

export async function sendCredentialsEmail({
    to,
    firstName,
    lastName,
    password,
    role,
}: SendCredentialsOptions) {
    const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT || '465'),
        secure: true, // must be true for 465
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
        },
    });
    const appName = process.env.APP_NAME || 'Palate';
    const loginUrl = process.env.LOGIN_URL || 'http://localhost:3000/auth/login';

    const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2>Welcome to ${appName}, ${firstName} ${lastName}!</h2>
      <p>An account has been created for you. You can now log in using the credentials below:</p>
      <table style="border-collapse: collapse; width: 100%; margin: 20px 0;">
        <tr>
          <td style="padding: 8px 0;"><strong>Email:</strong></td>
          <td>${to}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0;"><strong>Password:</strong></td>
          <td><code style="background: #f4f4f4; padding: 4px 8px; border-radius: 4px;">${password}</code></td>
        </tr>
        ${role ? `<tr><td style="padding: 8px 0;"><strong>Role:</strong></td><td>${role.replace('ROLE_', '')}</td></tr>` : ''}
      </table>
      <p><a href="${loginUrl}" style="background: #10b981; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px;">Log in now</a></p>
      <p>For security reasons, we recommend changing your password after your first login.</p>
      <hr style="margin: 30px 0;" />
      <p style="font-size: 12px; color: #666;">If you did not expect this email, please ignore it.</p>
    </div>
  `;

    try {
        await transporter.sendMail({
            from: `"${appName}" <${process.env.SMTP_FROM || process.env.SMTP_USER}>`,
            to,
            subject: `Your ${appName} account credentials`,
            text: `Hello ${firstName} ${lastName},\n\nAn account has been created for you.\n\nEmail: ${to}\nPassword: ${password}\n\nLogin at: ${loginUrl}\n\nWe recommend changing your password after first login.`,
            html: htmlContent,
        });
        return { success: true };
    } catch (error) {
        console.error('Failed to send credentials email:', error);
        return { success: false, error };
    }
}